name: Nodejs CI

# The workflow was triggered 163 times via automatically.

on:
  # schedule:
  # - cron: '12 17 * * 1'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm run
      run: |
        npm i
        npm run lint --if-present
        npm test --if-present
        npm i --omit=dev
        [[ -e index.mjs ]] && node index.mjs || echo -n ''
        [[ -e index.js ]] && node index.js || echo -n ''
      env:
        CI: true
        ENV: test
